# Generated by Django 5.2 on 2025-08-11 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('description', models.TextField(verbose_name='descrição')),
                ('category', models.CharField(choices=[('rule', 'Regra'), ('learning_goal', 'Objetivo de Aprendizagem'), ('activity', 'Atividade/Evento'), ('other', 'Outro')], max_length=20, verbose_name='categoria')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em curso'), ('done', 'Cumprido')], default='pending', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_decisions', to='classes.class', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Decisão de Conselho',
                'verbose_name_plural': 'Decisões de Conselho',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='texto')),
                ('date_submitted', models.DateField(auto_now_add=True, verbose_name='data de submissão')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('taken_to_council', 'Levado a Conselho'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='estado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_proposals', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_proposals', to='classes.class', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Proposta de Aluno',
                'verbose_name_plural': 'Propostas de Alunos',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
