# Generated by Django 5.2 on 2025-04-26 17:47

from django.db import migrations
# Removed: from django.contrib.auth.management import create_permissions

# Define the group names based on User.ROLE_CHOICES
GROUP_NAMES = ['aluno', 'professor', 'admin', 'encarregado']

def create_groups(apps, schema_editor):
    """Creates the default groups needed for the application."""
    Group = apps.get_model('auth', 'Group')
    # Removed Permission model retrieval as it's not used directly here
    # Permission = apps.get_model('auth', 'Permission') 

    # Removed the explicit create_permissions loop
    # Django's migrate command handles permission creation automatically.

    print("Creating default groups...") # Added print statement for clarity
    for group_name in GROUP_NAMES:
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f"  - Created group: {group_name}")
        else:
            print(f"  - Group already exists: {group_name}")
        # Optionally assign default permissions to groups here if needed later
        # Example:
        # try:
        #     Permission = apps.get_model('auth', 'Permission') 
        #     view_perm = Permission.objects.get(codename='view_some_model')
        #     group.permissions.add(view_perm)
        # except Permission.DoesNotExist:
        #     print(f"Warning: Permission 'view_some_model' not found for group {group_name}")

def remove_groups(apps, schema_editor):
    """Removes the groups created in the forward migration."""
    Group = apps.get_model('auth', 'Group')
    print(f"Deleting groups: {', '.join(GROUP_NAMES)}...") # Added print statement
    deleted_count, _ = Group.objects.filter(name__in=GROUP_NAMES).delete()
    print(f"  - Deleted {deleted_count} groups.")


class Migration(migrations.Migration):

    dependencies = [
        # Ensure this runs after the initial auth migrations 
        # and after the previous user migration.
        ('auth', '__latest__'), # Explicit dependency on auth app migrations
        ('users', '0003_guardianrelation'),
    ]

    operations = [
        # Run the function to create groups
        migrations.RunPython(create_groups, reverse_code=remove_groups),
    ]
