# Generated by Django 5.2 on 2025-08-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição/tema')),
                ('state', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='active', max_length=20, verbose_name='estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data fim prevista')),
                ('product_description', models.CharField(blank=True, max_length=255, verbose_name='produto final previsto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='membros')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='classes.class', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='data limite')),
                ('state', models.CharField(choices=[('todo', 'Por fazer'), ('in_progress', 'Em progresso'), ('done', 'Feito')], default='todo', max_length=20, verbose_name='estado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='projeto')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_responsible', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'Tarefa de Projeto',
                'verbose_name_plural': 'Tarefas de Projeto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
