[tool.black]
target-version = ["py311"]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E","F","I","W"]
ignore = []
exclude = [
  ".venv",
  "venv",
  "migrations",
  "static",
]


