# Generated by Django 5.2 on 2025-04-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('text', models.TextField(default='Default text - please update', verbose_name='text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['template', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_complete', models.FloatField(default=0, help_text='Automatically calculated percentage of completed items.', verbose_name='percentage complete')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'Student Checklist Status',
                'verbose_name_plural': 'Student Checklist Statuses',
                'ordering': ['student_class', 'student', 'template'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VALIDATED', 'Validated')], default='NOT_STARTED', max_length=20, verbose_name='status')),
                ('marked_at', models.DateTimeField(auto_now=True, verbose_name='marked at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Checklist Mark',
                'verbose_name_plural': 'Checklist Marks',
                'ordering': ['student', 'item__order'],
            },
        ),
    ]
