# Generated by Django 5.2 on 2025-04-29 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmark',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'aluno'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_checklist_statuses', to='classes.class', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='checklists.checklisttemplate', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistmark',
            unique_together={('student', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='checkliststatus',
            unique_together={('template', 'student', 'student_class')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('template', 'code')},
        ),
    ]
