# Generated by Django 5.2 on 2025-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_checklistmark_unique_together'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='checklist_templates', to='classes.class', verbose_name='Associated Classes'),
        ),
    ]
