# Generated by Django 5.2 on 2025-09-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_checklisttemplate_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='contracted_in_council',
            field=models.BooleanField(default=False, help_text='Mark if this objective foi contratualizado em Conselho de Cooperação Educativa.', verbose_name='negotiated in council'),
        ),
    ]
