# Generated by Django 5.2 on 2025-09-25 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_checklistitem_contracted_in_council'),
        ('classes', '0003_classmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['name', '-version'], 'verbose_name': 'Checklist Template', 'verbose_name_plural': 'Checklist Templates'},
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_checklist_templates', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_template_name_version'),
        ),
    ]
