# Generated by Django 5.2 on 2025-09-25 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_alter_checklisttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkliststatus',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('needs_revision', 'Needs revision')], default='draft', max_length=20, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='student_notes',
            field=models.TextField(blank=True, verbose_name='student notes'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='template_version',
            field=models.PositiveIntegerField(default=1, verbose_name='template version'),
        ),
    ]
