# Generated by Django 5.2 on 2025-04-26 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['year', 'name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Name of the class, e.g., "5º A", "Turma Azul".', max_length=100, verbose_name='class name'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'aluno'}, related_name='classes_attended', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'professor'}, related_name='classes_taught', to=settings.AUTH_USER_MODEL, verbose_name='teachers'),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(help_text='Starting year of the academic year (e.g., 2024 for 2024/2025) or the grade level (e.g., 5 for 5th grade).', verbose_name='academic year'),
        ),
    ]
