# Generated by Django 5.2 on 2025-05-06 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GOSTEI', 'Gostei'), ('ERRO', 'Encontrei um erro'), ('SUGIRO', 'Sugiro')], default='SUGIRO', max_length=10, verbose_name='categoria')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('page_url', models.CharField(blank=True, help_text='Se aplicável, a página onde o erro ocorreu ou a que a sugestão se refere.', max_length=255, null=True, verbose_name='URL da página (opcional)')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDO', 'Concluído'), ('REJEITADO', 'Rejeitado')], default='NOVO', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infantinho_feedback_items', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infantinho_feedback_items_turma', to='classes.class', verbose_name='turma (opcional)')),
            ],
            options={
                'verbose_name': 'Item de Feedback (Infantinho)',
                'verbose_name_plural': 'Itens de Feedback (Infantinho)',
                'ordering': ['-created_at'],
            },
        ),
    ]
