# Generated by Django 5.2 on 2025-04-29 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diarysession',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_sessions', to='classes.class', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diary.diarysession'),
        ),
    ]
