# Generated by Django 5.2 on 2025-04-23 20:41

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='motivo_remocao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='removido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='removido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_removidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='subcategoria_diario',
            field=models.CharField(blank=True, choices=[('GOSTEI', 'Gostei'), ('NAO_GOSTEI', 'Não Gostei'), ('QUEREMOS', 'Queremos'), ('FIZEMOS', 'Fizemos')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='visibilidade',
            field=models.CharField(choices=[('INTERNA', 'Apenas membros da turma'), ('PUBLICA', 'Público (futuro)')], default='INTERNA', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DIARIO', 'Diário de Turma'), ('AVISO', 'Aviso'), ('PROJETO', 'Projeto'), ('OUTRO', 'Outro')], default='DIARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
