# Generated by Django 5.2 on 2025-04-24 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_motivo_remocao_comment_removido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='motivo_remocao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='removido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='removido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_removidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('REMOVER_POST', 'Remover Post'), ('EDITAR_POST', 'Editar Post'), ('REMOVER_COMMENT', 'Remover Comentário'), ('EDITAR_COMMENT', 'Editar Comentário')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('conteudo_snapshot', models.TextField(blank=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
