# Generated by Django 5.2 on 2025-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_motivo_remocao_post_removido_post_removido_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='acao',
            field=models.CharField(choices=[('REMOVER_POST', 'Remover Post'), ('EDITAR_POST', 'Editar Post'), ('REMOVER_COMMENT', 'Remover Comentário'), ('EDITAR_COMMENT', 'Editar Comentário'), ('RESTAURAR_POST', 'Restaurar Post')], max_length=20),
        ),
    ]
