# Generated by Django 5.2 on 2025-04-29 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='removido_por',
            field=models.ForeignKey(blank=True, help_text='User who removed the comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_removidos', to=settings.AUTH_USER_MODEL, verbose_name='removed by'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.comment', verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who performed the moderation action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='moderator'),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the post for publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='removido_por',
            field=models.ForeignKey(blank=True, help_text='User who removed the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_removidos', to=settings.AUTH_USER_MODEL, verbose_name='removed by'),
        ),
        migrations.AddField(
            model_name='post',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='classes.class', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post'),
        ),
    ]
