# Generated by Django 5.2 on 2025-05-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='classes.class', verbose_name='class'),
        ),
    ]
