# Generated by Django 5.2 on 2025-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='acao',
            field=models.CharField(choices=[('REMOVER_POST', 'Remover Post'), ('RESTAURAR_POST', 'Restaurar Post'), ('REMOVER_COMMENT', 'Remover Comentário')], help_text='The type of moderation action performed.', max_length=20, verbose_name='action'),
        ),
    ]
