# Generated by Django 5.2 on 2025-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_moderationlog_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DIARIO', 'Diário de Turma'), ('TEA', 'Registo do Trabalho de Estudo Autónomo'), ('PROJETO', 'Projeto Cooperativo'), ('CONSELHO', 'Conselho de Cooperação Educativa'), ('TRABALHO', 'Partilha de Produções'), ('AVISO', 'Aviso ou Comunicação à Comunidade'), ('REFLEXAO', 'Reflexão sobre a Vida da Turma'), ('OUTRO', 'Outro Registo Pedagógico')], default='DIARIO', help_text='Escolhe o instrumento MEM que melhor corresponde ao registo.', max_length=20, verbose_name='category'),
        ),
    ]
