# Generated by Django 6.0.1 on 2026-02-02 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('anthropic', 'Anthropic'), ('local', 'Local/Custom')], default='openai', help_text='AI provider to use.', max_length=20, verbose_name='provider')),
                ('model', models.CharField(default='gpt-4o-mini', help_text='Model name (e.g., gpt-4o-mini, gemini-pro).', max_length=100, verbose_name='model')),
                ('max_tokens', models.IntegerField(default=2048, help_text='Maximum tokens per response.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)], verbose_name='max tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='Sampling temperature (0.0 = deterministic, 2.0 = very creative).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='temperature')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Default system prompt for the AI assistant.', verbose_name='system prompt')),
                ('is_active', models.BooleanField(default=True, help_text='Whether AI assistant is enabled.', verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_instance', models.ForeignKey(blank=True, help_text='Optional class context for this conversation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='classes.class', verbose_name='class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=20, verbose_name='role')),
                ('content', models.TextField(help_text='The message content.', verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used for this message (if tracked).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tokens used')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
