# Generated by Django 6.0.1 on 2026-02-02 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_topic', models.CharField(max_length=200, verbose_name='tema da pergunta')),
                ('help_level_used', models.CharField(choices=[('nivel_1', 'Nível 1 - Pista/estratégia'), ('nivel_2', 'Nível 2 - Exemplo análogo'), ('nivel_3', 'Nível 3 - Resposta guiada')], max_length=20, verbose_name='nível de apoio usado')),
                ('student_success', models.BooleanField(default=False, verbose_name='aluno conseguiu')),
                ('used_collaboration', models.BooleanField(default=False, verbose_name='usou colaboração')),
                ('conversation_excerpt', models.TextField(blank=True, verbose_name='excerto da conversa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Interação',
                'verbose_name_plural': 'Logs de Interações',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_zdp_level', models.CharField(choices=[('autonomo', 'Autónomo - trabalha sozinho'), ('apoio_minimo', 'Com apoio mínimo - pistas'), ('apoio_moderado', 'Com apoio moderado - exemplos'), ('apoio_intenso', 'Com apoio intenso - guiação')], default='apoio_minimo', help_text='Nível de apoio que o aluno precisa atualmente', max_length=20, verbose_name='nível ZDP atual')),
                ('learns_best_with', models.JSONField(default=dict, help_text='Preferências: exemplos, imagens, passo-a-passo, colegas, etc.', verbose_name='aprende melhor com')),
                ('collaboration_success_rate', models.FloatField(default=0.0, help_text='0-1, calculado automaticamente', verbose_name='taxa de sucesso em colaboração')),
                ('strengths', models.JSONField(default=list, help_text='Domínios onde o aluno é autónomo', verbose_name='pontos fortes')),
                ('growth_areas', models.JSONField(default=list, help_text='Domínios que precisam de mais apoio', verbose_name='áreas de crescimento')),
                ('ai_interaction_count', models.PositiveIntegerField(default=0, verbose_name='número de interações com IA')),
                ('last_ai_topics', models.JSONField(default=list, help_text='Temas recentes para contexto', verbose_name='últimos tópicos com IA')),
                ('autonomy_progress', models.JSONField(default=dict, help_text='Por domínio: {dominio: {data: valor, ...}}', verbose_name='progresso de autonomia')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_collaborators', models.ManyToManyField(blank=True, related_name='collaborates_with', to=settings.AUTH_USER_MODEL, verbose_name='colegas preferidos para trabalho')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Aprendizagem',
                'verbose_name_plural': 'Perfis de Aprendizagem',
            },
        ),
    ]
