# Generated by Django 5.2 on 2025-09-17 11:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('persona', models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor'), ('guardian', 'Encarregado'), ('admin', 'Administrador'), ('staff', 'Equipa')], max_length=20)),
                ('origin_app', models.CharField(help_text='Identificador lógico da área onde a sessão começou (ex: "blog", "pit", "checklists").', max_length=50)),
                ('context_descriptor', models.CharField(blank=True, help_text='Descrição curta do contexto ativo (ex: "PIT 2.º período", "Projeto Energia").', max_length=120)),
                ('context_payload', models.JSONField(blank=True, default=dict, help_text='Dados complementares serializados para reconstruir rapidamente o contexto pedagógico.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('class_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='classes.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão IA',
                'verbose_name_plural': 'Sessões IA',
                'ordering': ('-last_interaction_at',),
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor'), ('guardian', 'Encarregado'), ('admin', 'Administrador'), ('staff', 'Equipa')], max_length=20)),
                ('origin_app', models.CharField(max_length=50)),
                ('raw_query', models.TextField(help_text='Texto original submetido pelo utilizador.')),
                ('optimized_prompt', models.TextField(blank=True)),
                ('optimizer_trace', models.JSONField(blank=True, default=dict)),
                ('intent_label', models.CharField(blank=True, max_length=120)),
                ('target_model', models.CharField(blank=True, max_length=40)),
                ('resolved_model', models.CharField(blank=True, max_length=40)),
                ('meta_context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('skipped', 'Ignorado'), ('errored', 'Erro')], default='pending', max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00000'))])),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ai.aiinteractionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido IA',
                'verbose_name_plural': 'Pedidos IA',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
                ('guardrail_decision', models.JSONField(blank=True, default=dict)),
                ('used_cache', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_log', to='ai.airequest')),
            ],
            options={
                'verbose_name': 'Resposta IA',
                'verbose_name_plural': 'Respostas IA',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GroupLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('focus_competencies', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('class_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_learning_profiles', to='classes.class')),
            ],
            options={
                'verbose_name': 'Perfil de Grupo',
                'verbose_name_plural': 'Perfis de Grupo',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='TeacherFocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_text', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_after', models.DateTimeField(blank=True, null=True)),
                ('class_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='classes.class')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foco Pedagógico',
                'verbose_name_plural': 'Focos Pedagógicos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', 'Utilizador'), ('class', 'Turma')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('max_requests', models.PositiveIntegerField(default=0)),
                ('max_cost', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00000'))])),
                ('requests_made', models.PositiveIntegerField(default=0)),
                ('cost_accumulated', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00000'))])),
                ('last_reset_at', models.DateTimeField(auto_now=True)),
                ('class_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_quotas', to='classes.class')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota IA',
                'verbose_name_plural': 'Quotas IA',
                'constraints': [models.UniqueConstraint(fields=('scope', 'user', 'class_context', 'period_start', 'period_end'), name='unique_ai_quota_per_scope_period')],
            },
        ),
        migrations.CreateModel(
            name='LearnerContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('needs', models.JSONField(blank=True, default=list)),
                ('mem_competencies', models.JSONField(blank=True, default=dict, help_text='Pontuações ou comentários por competência MEM (ex: autonomia, cooperação).')),
                ('last_pit_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_checklist_update', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='system', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('class_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_context_snapshots', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_context_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de Aprendizagem',
                'verbose_name_plural': 'Snapshots de Aprendizagem',
                'ordering': ('-refreshed_at',),
                'unique_together': {('student', 'class_context', 'source')},
            },
        ),
    ]
