# Generated by Django 5.2 on 2025-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponselog',
            name='user_feedback',
            field=models.CharField(blank=True, help_text='Resposta útil? valores possíveis: "helpful", "neutral", "not_helpful".', max_length=20),
        ),
    ]
