# Generated by Django 5.2 on 2025-08-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text='Identificador do período (ex.: "Semana 5 - Out 2025").', max_length=100, verbose_name='período')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('approved', 'Aprovado'), ('concluded', 'Concluído'), ('evaluated', 'Avaliado')], default='draft', max_length=20, verbose_name='estado')),
                ('general_objectives', models.TextField(blank=True, verbose_name='objetivos gerais')),
                ('self_evaluation', models.TextField(blank=True, verbose_name='autoavaliação do aluno')),
                ('teacher_evaluation', models.TextField(blank=True, verbose_name='avaliação do professor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_plans', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_plans', to='classes.class', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Plano Individual de Trabalho',
                'verbose_name_plural': 'Planos Individuais de Trabalho',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='disciplina/área')),
                ('state', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Feito'), ('validated', 'Validado')], default='pending', max_length=20, verbose_name='estado')),
                ('evidence_link', models.URLField(blank=True, verbose_name='ligação para evidência')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='feedback do professor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pit.individualplan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'Tarefa do Plano',
                'verbose_name_plural': 'Tarefas do Plano',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='individualplan',
            constraint=models.UniqueConstraint(fields=('student', 'student_class', 'period_label'), name='unique_plan_per_period_per_class'),
        ),
    ]
