# Generated by Django 5.2 on 2025-09-24 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classmembership'),
        ('pit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualplan',
            name='origin_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_children', to='pit.individualplan', verbose_name='plano de origem'),
        ),
        migrations.AddField(
            model_name='individualplan',
            name='pendings_imported',
            field=models.BooleanField(default=False, verbose_name='pendências importadas'),
        ),
        migrations.AddField(
            model_name='individualplan',
            name='suggestions_imported',
            field=models.BooleanField(default=False, verbose_name='sugestões importadas'),
        ),
        migrations.AddField(
            model_name='individualplan',
            name='template_version',
            field=models.PositiveIntegerField(default=1, verbose_name='versão do modelo'),
        ),
        migrations.CreateModel(
            name='PitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('cycle_label', models.CharField(blank=True, help_text='Identificador pedagógico do modelo (ex.: 2.º ciclo).', max_length=100, verbose_name='ciclo/ano')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicado/ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pit_templates', to=settings.AUTH_USER_MODEL, verbose_name='autor do modelo')),
                ('student_class', models.ForeignKey(blank=True, help_text='Opcionalmente restringe o modelo a uma turma específica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pit_templates', to='classes.class', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Modelo de PIT',
                'verbose_name_plural': 'Modelos de PIT',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='individualplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='pit.pittemplate', verbose_name='modelo aplicado'),
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título da secção')),
                ('area_code', models.CharField(blank=True, max_length=50, verbose_name='código da área/disciplina')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('default_description', models.TextField(blank=True, verbose_name='descrição base')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pit.pittemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'Secção do Modelo',
                'verbose_name_plural': 'Secções do Modelo',
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto da sugestão')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_pending', models.BooleanField(default=False, verbose_name='transportar como pendente')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='pit.templatesection', verbose_name='secção')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='pit.pittemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'Sugestão do Modelo',
                'verbose_name_plural': 'Sugestões do Modelo',
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pittemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('student_class__isnull', False)), fields=('student_class', 'version'), name='unique_template_version_per_class'),
        ),
    ]
