# Generated by Django 5.2 on 2025-09-24 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0002_individualplan_origin_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated_from_template', 'Gerado a partir do modelo'), ('updated', 'Atualizado'), ('status_change', 'Mudança de estado'), ('comment', 'Comentário')], max_length=50, verbose_name='ação')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='pit.individualplan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'Log do Plano',
                'verbose_name_plural': 'Logs do Plano',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título da secção')),
                ('area_code', models.CharField(blank=True, max_length=50, verbose_name='código da área/disciplina')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pit.individualplan', verbose_name='plano')),
                ('template_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_sections', to='pit.templatesection', verbose_name='secção do modelo')),
            ],
            options={
                'verbose_name': 'Secção do Plano',
                'verbose_name_plural': 'Secções do Plano',
                'ordering': ['plan', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
                ('origin', models.CharField(choices=[('template', 'Modelo'), ('council', 'Conselho'), ('pending', 'Pendência'), ('manual', 'Manual')], default='template', max_length=20, verbose_name='origem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_pending', models.BooleanField(default=False, verbose_name='marcar como pendente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_suggestions', to='pit.plantask', verbose_name='tarefa de origem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='pit.individualplan', verbose_name='plano')),
                ('template_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_suggestions', to='pit.templatesuggestion', verbose_name='sugestão de modelo')),
            ],
            options={
                'verbose_name': 'Sugestão do Plano',
                'verbose_name_plural': 'Sugestões do Plano',
                'ordering': ['plan', 'order', 'id'],
            },
        ),
    ]
