# Generated by Django 5.2 on 2025-04-29 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'aluno'}, related_name='classes_attended', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'professor'}, related_name='classes_taught', to=settings.AUTH_USER_MODEL, verbose_name='teachers'),
        ),
    ]
