# Generated by Codex refactor to introduce ClassMembership model
from django.db import migrations, models
from django.conf import settings


def copy_memberships(apps, schema_editor):
    Class = apps.get_model('classes', 'Class')
    ClassMembership = apps.get_model('classes', 'ClassMembership')
    for turma in Class.objects.all():
        student_ids = turma.students.values_list('id', flat=True)
        teacher_ids = turma.teachers.values_list('id', flat=True)

        for user_id in student_ids:
            ClassMembership.objects.get_or_create(
                class_instance_id=turma.id,
                user_id=user_id,
                defaults={'role': 'student'},
            )

        for user_id in teacher_ids:
            ClassMembership.objects.get_or_create(
                class_instance_id=turma.id,
                user_id=user_id,
                defaults={'role': 'teacher'},
            )


def remove_memberships(apps, schema_editor):
    ClassMembership = apps.get_model('classes', 'ClassMembership')
    ClassMembership.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor'), ('guardian', 'Encarregado de Educação'), ('assistant', 'Assistente')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Marks whether the membership is active.', verbose_name='is active')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='assigned_class_memberships', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('class_instance', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='memberships', to='classes.class', verbose_name='class')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Class membership',
                'verbose_name_plural': 'Class memberships',
                'unique_together': {('class_instance', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='classmembership',
            index=models.Index(fields=['class_instance', 'role'], name='classes_cla_class_i_7167c4_idx'),
        ),
        migrations.AddIndex(
            model_name='classmembership',
            index=models.Index(fields=['user', 'role'], name='classes_cla_user_id_ea5a9e_idx'),
        ),
        migrations.RunPython(copy_memberships, remove_memberships),
    ]
