# Generated by Django 5.2 on 2025-04-22 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmark',
            name='marcado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='checklists.checkliststatus'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate'),
        ),
    ]
