# Generated by Django 5.2 on 2025-04-29 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistmark',
            options={'ordering': ['status_record__student', 'item__order'], 'verbose_name': 'Checklist Mark', 'verbose_name_plural': 'Checklist Marks'},
        ),
        migrations.RenameField(
            model_name='checklistmark',
            old_name='status',
            new_name='mark_status',
        ),
        migrations.AlterUniqueTogether(
            name='checklistmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='status_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='checklists.checkliststatus', verbose_name='checklist status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='teacher_validated',
            field=models.BooleanField(default=False, verbose_name='teacher validated'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='marked at'),
        ),
        migrations.RemoveField(
            model_name='checklistmark',
            name='student',
        ),
    ]
