# Generated by Django 5.2 on 2025-04-24 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistmark',
            old_name='concluido',
            new_name='validacao_professor',
        ),
        migrations.RenameField(
            model_name='checkliststatus',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='checklistmark',
            name='data',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='contratualizado_em_conselho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='criterios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistmark',
            name='estado',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_progresso', 'Em progresso'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to='classes.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='disciplina',
            field=models.CharField(default='Português', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='ano',
            field=models.CharField(max_length=20),
        ),
    ]
