# Generated by Django 5.2 on 2025-04-26 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_rename_concluido_checklistmark_validacao_professor_and_more'),
        ('classes', '0003_alter_class_options_alter_class_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename fields first to avoid conflicts and preserve data
        migrations.RenameField(
            model_name='checklisttemplate',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='checklisttemplate',
            old_name='ano',
            new_name='grade_level',
        ),
        migrations.RenameField(
            model_name='checklisttemplate',
            old_name='disciplina',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='checklisttemplate',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='checklisttemplate',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='checklisttemplate',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='criterios',
            new_name='criteria',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='ordem',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='contratualizado_em_conselho',
            new_name='council_agreed',
        ),
        migrations.RenameField(
            model_name='checkliststatus',
            old_name='aluno',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='checkliststatus',
            old_name='classe',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='checkliststatus',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='checklistmark',
            old_name='estado',
            new_name='mark_status',
        ),
        migrations.RenameField(
            model_name='checklistmark',
            old_name='comentario',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='checklistmark',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='checklistmark',
            old_name='marcado_por',
            new_name='marked_by',
        ),
        migrations.RenameField(
            model_name='checklistmark',
            old_name='validacao_professor',
            new_name='teacher_validated',
        ),
        # Add the new field that wasn't a rename
        migrations.AddField(
            model_name='checklistmark',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='marked at'),
        ),
        # Now apply alterations to the (now renamed) fields and models
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['template', 'order', 'description'], 'verbose_name': 'Checklist Item', 'verbose_name_plural': 'Checklist Items'},
        ),
        migrations.AlterModelOptions(
            name='checklistmark',
            options={'ordering': ['status', 'item__order'], 'verbose_name': 'Checklist Item Mark', 'verbose_name_plural': 'Checklist Item Marks'},
        ),
        migrations.AlterModelOptions(
            name='checkliststatus',
            options={'ordering': ['student_class', 'student', 'template'], 'verbose_name': 'Student Checklist Status', 'verbose_name_plural': 'Student Checklist Statuses'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['grade_level', 'subject', 'name'], 'verbose_name': 'Checklist Template', 'verbose_name_plural': 'Checklist Templates'},
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='grade_level',
            field=models.IntegerField(blank=True, help_text='The grade level this template applies to (e.g., 5 for 5th grade). Leave blank if multi-grade.', null=True, verbose_name='grade level'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='name',
            field=models.CharField(help_text='Name of the checklist template, e.g., "Mathematics 7th Grade".', max_length=150, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='subject',
            field=models.CharField(help_text='The subject area, e.g., "Portuguese", "Mathematics", "Science".', max_length=100, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or general guidelines for this checklist.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.CharField(help_text='The description of the learning objective or item.', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='criteria',
            field=models.TextField(blank=True, help_text='Optional: Specific criteria or descriptors for achieving this item.', verbose_name='criteria'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which this item appears in the checklist.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='council_agreed',
            field=models.BooleanField(default=False, help_text='Was this item specifically agreed upon as a focus in a class council?', verbose_name='agreed in council'),
        ),
         migrations.AlterField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='mark_status',
            field=models.CharField(choices=[('not_started', 'Não iniciado'), ('in_progress', 'Em progresso'), ('completed', 'Concluído')], default='not_started', max_length=20, verbose_name='mark status'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_made', to=settings.AUTH_USER_MODEL, verbose_name='marked by'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='teacher_validated',
            field=models.BooleanField(default=False, help_text="Indicates if a teacher has validated the 'completed' status.", verbose_name='teacher validated'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='checklists.checklistitem', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='checklistmark',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='checklists.checkliststatus', verbose_name='checklist status'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistmark',
            unique_together={('status', 'item')},
        ),
        migrations.AlterField(
            model_name='checkliststatus',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='checkliststatus',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_checklist_statuses', to='classes.class', verbose_name='class'),
        ),
         migrations.AlterField(
            model_name='checkliststatus',
            name='percent_complete',
            field=models.FloatField(default=0, help_text='Automatically calculated percentage of completed items.', verbose_name='percentage complete'),
        ),
        migrations.AlterField(
            model_name='checkliststatus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='checklists.checklisttemplate', verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='checkliststatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststatus',
            unique_together={('template', 'student', 'student_class')},
        ),
    ]
