# Generated by Django 5.2 on 2025-04-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklistmark_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistmark',
            unique_together={('status_record', 'item')},
        ),
    ]
