# Generated by Django 5.2 on 2025-04-30 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='O endereço de email Microsoft do aluno a ser pré-aprovado.', max_length=254, unique=True, verbose_name='Email do Aluno')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('status', models.CharField(choices=[('Pending', 'Pendente'), ('Claimed', 'Reivindicado')], default='Pending', help_text='Estado da pré-aprovação (Pendente ou Reivindicado após login do aluno).', max_length=10, verbose_name='Estado')),
                ('date_claimed', models.DateTimeField(blank=True, null=True, verbose_name='Data de Reivindicação')),
                ('added_by', models.ForeignKey(blank=True, help_text='Utilizador (Admin/Professor) que adicionou este email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_preapproved_students', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado Por')),
                ('claimed_by', models.ForeignKey(blank=True, help_text='O utilizador Aluno que corresponde a este email após o login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_preapprovals', to=settings.AUTH_USER_MODEL, verbose_name='Reivindicado Por')),
                ('class_instance', models.ForeignKey(help_text='A turma à qual o aluno será associado.', on_delete=django.db.models.deletion.CASCADE, related_name='preapproved_students', to='classes.class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aluno Pré-Aprovado',
                'verbose_name_plural': 'Alunos Pré-Aprovados',
                'ordering': ['class_instance', 'email'],
            },
        ),
    ]
