# Generated by Django 5.2 on 2025-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preapprovedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force user to update the password after the next login.', verbose_name='must change password'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, help_text='Unique identifier provided by the school for students.', max_length=32, null=True, unique=True, verbose_name='student number'),
        ),
    ]
