# Generated by Django 5.2 on 2025-09-22 07:12

from django.db import migrations
from django.contrib.auth.hashers import make_password, check_password


def create_default_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')

    admin_group, _ = Group.objects.get_or_create(name='admin')
    for group_name in ('aluno', 'professor', 'encarregado'):
        Group.objects.get_or_create(name=group_name)

    user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'email': 'admin@infantinho.local',
            'is_staff': True,
            'is_superuser': True,
            'role': 'admin',
            'status': 'ativo',
            'must_change_password': True,
            'is_active': True,
        },
    )

    if created:
        user.password = make_password('admin')
        user.save(update_fields=['password'])
    else:
        updated = False
        if not user.is_superuser:
            user.is_superuser = True
            updated = True
        if not user.is_staff:
            user.is_staff = True
            updated = True
        if not user.is_active:
            user.is_active = True
            updated = True
        if not user.role:
            user.role = 'admin'
            updated = True
        if user.status != 'ativo':
            user.status = 'ativo'
            updated = True
        if not user.email:
            user.email = 'admin@infantinho.local'
            updated = True
        if check_password('admin', user.password) and not user.must_change_password:
            user.must_change_password = True
            updated = True
        if not user.has_usable_password():
            user.password = make_password('admin')
            user.must_change_password = True
            updated = True
        if updated:
            user.save()

    user.groups.add(admin_group)


def remove_default_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin', email='admin@infantinho.local').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_must_change_password_user_student_number'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin),
    ]
